---
- name: Install
  apt: name={{ item }}
  with_items:
    - clamav
    - clamav-daemon

- name: Setup config
  template:
      src=clamd.conf.j2
      dest=/etc/clamav/clamd.conf

- name: Get definitions
  command: freshclam

- name: Setup virus definition service
  service:
    name=clamav-freshclam
    state=restarted
    enabled=yes

- name: Setup virus scanning service
  service:
    name=clamav-daemon
    state=restarted
    enabled=yes
