---
- name: Install
  apt: name={{ item }}
  with_items:
    - clamav
    - clamav-daemon
  tags:
    - clamav

- name: Setup /etc/clamav/clamd.conf
  template:
      src=clamd.conf.j2
      dest=/etc/clamav/clamd.conf
  notify: Restart clamav
  tags:
    - clamav

- name: Setup /etc/clamav/freshclam.conf
  template:
      src=freshclam.conf.j2
      dest=/etc/clamav/freshclam.conf
  notify: Restart clamav
  tags:
    - clamav

- name: copy definitions from file
  copy:
    src={{ item }}
    dest=/var/lib/clamav/
    owner=clamav
    group=clamav
    mode=0644
  with_items:
    - main.cvd
    - daily.cvd
  when: clamav_definition_install_method == 'file'
  tags:
    - clamav
  notify: Restart clamav

- name: copy defintions from s3
  s3: bucket={{ clamav_s3_bucket }} object=/clamav/{{ item }} dest=/var/lib/clamav/{{ item }} mode=get
  with_items:
    - main.cvd
    - daily.cvd
  when: clamav_definition_install_method == 's3'
  tags:
    - clamav
  notify: Restart clamav

- name: copy defintions from internet
  get_url: url={{ clamav_web_server }}{{ item }} dest=/var/lib/clamav/{{ item }} mode=0644
  with_items:
    - main.cvd
    - daily.cvd
  when: clamav_definition_install_method == 'web'
  tags:
    - clamav
  notify: Restart clamav

- name: ensure permissions on defintions are correct
  file:
    path=/var/lib/clamav/{{ item }}
    owner=clamav
    group=clamav
    mode=0644
  with_items:
    - main.cvd
    - daily.cvd
  tags:
    - clamav
