---
- name: Install
  apt: name={{ item }}
  with_items:
    - clamav
    - clamav-daemon

- name: Setup config
  template:
      src=clamd.conf.j2
      dest=/etc/clamav/clamd.conf
  notify: Restart clamav

- copy:
    src={{ item }}
    dest=/var/lib/clamav/
    owner=clamav
    group=clamav
    mode=0644
  with_items:
    - main.cvd
    - daily.cvd
